source 'http://gemcutter.org'

require 'rubygems'
gem 'rake', '>=0.9.2.2'
#gem 'mongo', '1.3.1'
gem 'rails'#, '3.2.9'
gem 'mongo'
#gem 'rails'
#gem 'mongo_mapper-rails3', :require => "mongo_mapper"
gem 'mongo_mapper', "~> 0.12.0"#, "~> 0.10.1"
gem 'mongo_session_store'
gem 'bson'
gem 'bson_ext'
gem "joint", "~> 0.6.2"
gem 'thin'
#gem 'rails3-generators' # https://github.com/indirect/rails3-generators/
gem 'json'
gem 'factory_girl_rails', "~> 3.0"
gem 'rack'
gem 'devise', '~> 1.5.4'
gem 'mm-devise','<= 1.9'
#gem 'devise-encryptable'
gem 'wand'
gem 'mm-sanitize', :path => "jobs/"
gem 'rest-client'
gem "will_paginate", "~> 3.0.pre2"
gem 'jquery-rails', '>= 1.0.12'
gem 'mechanize'
gem 'bio'
gem 'xml-simple'
gem 'jquery_datepicker'
#gem 'mm-optimistic_locking'
#gem 'devise_shibboleth_authenticatable'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'certified' # for the SSL error
gem 'interactive_editor'

# to allow use of vim in the console
# as well as better errors
group :development do
  gem 'letters', :require => "letters/patch/rails"
  gem "better_errors"
end
gem "binding_of_caller"
gem "coderay"

# for running jobs in queue
gem 'sidekiq'
gem 'slim'
gem 'sinatra', :require => nil

# for some nice errors
# https://github.com/charliesome/better_errors

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
